default:
  APPLICATION_URL_INCORP: $APPLICATION_URL/liquor/license
  TEMPLATE_PATH: ../templates
  TOB_API_URL: http://tob-api:8080/api/v2
  TOB_APP_URL: http://localhost:8080
  LIQUOR_WALLET_SEED: ministry_liq_dev_000000000000000
