- name: incorporation.permitify
  version: '1.0.3'
  attributes:
    - corp_num
    - registration_date
    - entity_type
    - entity_status
    - entity_status_effective
    - entity_name_effective
    - address_line_1
    - address_line_2
    - addressee
    - city
    - country
    - legal_name
    - postal_code
    - province

# - name: doing_business_as.permitify
#   version: '1.0.3'
#   attributes:
#     - corp_num
#     - dba_corp_num
#     - doing_business_as_name
#     - address_line_1
#     - address_line_2
#     - addressee
#     - city
#     - country
#     - postal_code
#     - province
