version: '3'
services:

  web:
    build: .
    entrypoint: enter
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
    links:
      - postgres
    volumes:
      - ./src:/app
    ports:
      - 8000:8000

  postgres:
    image: postgres
    ports:
      - '5432:5432'