version: '3'
services:

  bc_registries:
    image: permitify
    entrypoint: enter
    command: bc_registries python manage.py runserver 0.0.0.0:3000
    environment:
      # DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
      THE_ORG_BOOK_BASE_URL: 'https://django-devex-von-dev.pathfinder.gov.bc.ca/api/v1'
    # links:
    #   - postgres
    volumes:
      # - ./src:/app
      # - ./site_templates:/app/site_templates
      - bc_registries_wallet:/app/.indy_client/wallet
    ports:
      - 3000:3000


  worksafe_bc:
    image: permitify
    entrypoint: enter
    command: worksafe_bc python manage.py runserver 0.0.0.0:4000
    environment:
      # DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
      THE_ORG_BOOK_BASE_URL: 'https://django-devex-von-dev.pathfinder.gov.bc.ca/api/v1'
    # links:
    #   - postgres
    volumes:
      # - ./src:/app
      # - ./site_templates:/app/site_templates
      - worksafe_bc_wallet:/app/.indy_client/wallet
    ports:
      - 4000:4000



  # Example new service:
  
  # liquor_board:
  #   image: permitify
  #   entrypoint: enter
  #   command: liquor_board python manage.py runserver 0.0.0.0:5000
  #   environment:
  #     # DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
  #     THE_ORG_BOOK_BASE_URL: 'https://django-devex-von-dev.pathfinder.gov.bc.ca/api/v1'
  #   # links:
  #   #   - postgres
  #   volumes:
  #     # - ./src:/app
  #     # - ./site_templates:/app/site_templates
  #     - worksafe_bc_wallet:/app/.indy_client/wallet
  #   ports:
  #     - 5000:5000


  # postgres:
  #   image: postgres
  #   ports:
  #     - '5432:5432'

volumes:
  worksafe_bc_wallet:
  bc_registries_wallet:
  # liquor_board: