version: '3'
services:

  bc_registries:
    image: permitify
    environment:
      PYTHON_ENV: development
      THE_ORG_BOOK_API_URL: ${THE_ORG_BOOK_API_URL}
      THE_ORG_BOOK_APP_URL: ${THE_ORG_BOOK_APP_URL}
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: bc_registries
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8080
      APPLICATION_URL: ${APPLICATION_URL}:5000
      INDY_WALLET_SEED: ${INDY_WALLET_SEED}1
      TOB_INDY_SEED: ${TOB_INDY_SEED}
      LEDGER_URL: ${LEDGER_URL}
      WALLET_USER_ID: ${WALLET_USER_ID}
      WALLET_PASSWORD: ${WALLET_PASSWORD}
      INDY_WALLET_URL: ${INDY_WALLET_URL}
      INDY_WALLET_TYPE: ${INDY_WALLET_TYPE}
      REDIS_SERVICE_NAME: ${REDIS_SERVICE_NAME}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      DEBUG: ${DEBUG}
      RUST_LOG: ${RUST_LOG}
      RUST_BACKTRACE: ${RUST_BACKTRACE}
    links:
      - redis
    volumes:
      - bc_registries_wallet:/home/indy/.indy_client/wallet
    networks:
      - tob_tob
      - tob_wallet-tob
      - permitify
    ports:
      - 5000:8080

  worksafe_bc:
    image: permitify
    environment:
      PYTHON_ENV: development
      THE_ORG_BOOK_API_URL: ${THE_ORG_BOOK_API_URL}
      THE_ORG_BOOK_APP_URL: ${THE_ORG_BOOK_APP_URL}
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: worksafe_bc
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8080
      APPLICATION_URL: ${APPLICATION_URL}:5001
      INDY_WALLET_SEED: ${INDY_WALLET_SEED}2
      TOB_INDY_SEED: ${TOB_INDY_SEED}
      LEDGER_URL: ${LEDGER_URL}
      WALLET_USER_ID: ${WALLET_USER_ID}
      WALLET_PASSWORD: ${WALLET_PASSWORD}
      INDY_WALLET_URL: ${INDY_WALLET_URL}
      INDY_WALLET_TYPE: ${INDY_WALLET_TYPE}
      REDIS_SERVICE_NAME: ${REDIS_SERVICE_NAME}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      DEBUG: ${DEBUG}
      RUST_LOG: ${RUST_LOG}
      RUST_BACKTRACE: ${RUST_BACKTRACE}
    links:
      - redis
    volumes:
      - worksafe_bc_wallet:/home/indy/.indy_client/wallet
    networks:
      - tob_tob
      - tob_wallet-tob
      - permitify
    ports:
      - 5001:8080

  ministry_of_finance:
    image: permitify
    environment:
      PYTHON_ENV: development
      THE_ORG_BOOK_API_URL: ${THE_ORG_BOOK_API_URL}
      THE_ORG_BOOK_APP_URL: ${THE_ORG_BOOK_APP_URL}
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: ministry_of_finance
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8080
      APPLICATION_URL: ${APPLICATION_URL}:5002
      INDY_WALLET_SEED: ${INDY_WALLET_SEED}3
      TOB_INDY_SEED: ${TOB_INDY_SEED}
      LEDGER_URL: ${LEDGER_URL}
      WALLET_USER_ID: ${WALLET_USER_ID}
      WALLET_PASSWORD: ${WALLET_PASSWORD}
      INDY_WALLET_URL: ${INDY_WALLET_URL}
      INDY_WALLET_TYPE: ${INDY_WALLET_TYPE}
      REDIS_SERVICE_NAME: ${REDIS_SERVICE_NAME}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      DEBUG: ${DEBUG}
      RUST_LOG: ${RUST_LOG}
      RUST_BACKTRACE: ${RUST_BACKTRACE}
    links:
      - redis
    volumes:
      - ministry_of_finance_wallet:/home/indy/.indy_client/wallet
    networks:
      - tob_tob
      - tob_wallet-tob
      - permitify
    ports:
      - 5002:8080

  fraser_valley_health_authority:
    image: permitify
    environment:
      PYTHON_ENV: development
      THE_ORG_BOOK_API_URL: ${THE_ORG_BOOK_API_URL}
      THE_ORG_BOOK_APP_URL: ${THE_ORG_BOOK_APP_URL}
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: fraser_valley_health_authority
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8080
      APPLICATION_URL: ${APPLICATION_URL}:5003
      INDY_WALLET_SEED: ${INDY_WALLET_SEED}4
      TOB_INDY_SEED: ${TOB_INDY_SEED}
      LEDGER_URL: ${LEDGER_URL}
      WALLET_USER_ID: ${WALLET_USER_ID}
      WALLET_PASSWORD: ${WALLET_PASSWORD}
      INDY_WALLET_URL: ${INDY_WALLET_URL}
      INDY_WALLET_TYPE: ${INDY_WALLET_TYPE}
      REDIS_SERVICE_NAME: ${REDIS_SERVICE_NAME}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      DEBUG: ${DEBUG}
      RUST_LOG: ${RUST_LOG}
      RUST_BACKTRACE: ${RUST_BACKTRACE}
    links:
      - redis
    volumes:
      - fraser_valley_health_authority_wallet:/home/indy/.indy_client/wallet
    networks:
      - tob_tob
      - tob_wallet-tob
      - permitify
    ports:
      - 5003:8080

  city_of_surrey:
    image: permitify
    environment:
      PYTHON_ENV: development
      THE_ORG_BOOK_API_URL: ${THE_ORG_BOOK_API_URL}
      THE_ORG_BOOK_APP_URL: ${THE_ORG_BOOK_APP_URL}
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: city_of_surrey
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8080
      APPLICATION_URL: ${APPLICATION_URL}:5004
      INDY_WALLET_SEED: ${INDY_WALLET_SEED}5
      TOB_INDY_SEED: ${TOB_INDY_SEED}
      LEDGER_URL: ${LEDGER_URL}
      WALLET_USER_ID: ${WALLET_USER_ID}
      WALLET_PASSWORD: ${WALLET_PASSWORD}
      INDY_WALLET_URL: ${INDY_WALLET_URL}
      INDY_WALLET_TYPE: ${INDY_WALLET_TYPE}
      REDIS_SERVICE_NAME: ${REDIS_SERVICE_NAME}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      DEBUG: ${DEBUG}
      RUST_LOG: ${RUST_LOG}
      RUST_BACKTRACE: ${RUST_BACKTRACE}
    links:
      - redis
    volumes:
      - city_of_surrey_wallet:/home/indy/.indy_client/wallet
    networks:
      - tob_tob
      - tob_wallet-tob
      - permitify
    ports:
      - 5004:8080

  liquor_control_and_licensing_branch:
    image: permitify
    environment:
      PYTHON_ENV: development
      THE_ORG_BOOK_API_URL: ${THE_ORG_BOOK_API_URL}
      THE_ORG_BOOK_APP_URL: ${THE_ORG_BOOK_APP_URL}
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: liquor_control_and_licensing_branch
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8070
      APPLICATION_URL: ${APPLICATION_URL}:5005
      INDY_WALLET_SEED: ${INDY_WALLET_SEED}6
      TOB_INDY_SEED: ${TOB_INDY_SEED}
      LEDGER_URL: ${LEDGER_URL}
      WALLET_USER_ID: ${WALLET_USER_ID}
      WALLET_PASSWORD: ${WALLET_PASSWORD}
      INDY_WALLET_URL: ${INDY_WALLET_URL}
      INDY_WALLET_TYPE: ${INDY_WALLET_TYPE}
      REDIS_SERVICE_NAME: ${REDIS_SERVICE_NAME}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      DEBUG: ${DEBUG}
      RUST_LOG: ${RUST_LOG}
      RUST_BACKTRACE: ${RUST_BACKTRACE}
    links:
      - redis
    volumes:
      - liquor_control_and_licensing_branch_wallet:/home/indy/.indy_client/wallet
    networks:
      - tob_tob
      - tob_wallet-tob
      - permitify
    ports:
      - 5005:8070

  redis:
    image: redis
    networks:
      - permitify
    ports:
      - 6379:6379

  onbis:
    image: permitify
    environment:
      PYTHON_ENV: development
      THE_ORG_BOOK_API_URL: ${THE_ORG_BOOK_API_URL}
      THE_ORG_BOOK_APP_URL: ${THE_ORG_BOOK_APP_URL}
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: onbis
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8080
      APPLICATION_URL: ${APPLICATION_URL}:5006
      INDY_WALLET_SEED: ${INDY_WALLET_SEED}7
      TOB_INDY_SEED: ${TOB_INDY_SEED}
      LEDGER_URL: ${LEDGER_URL}
      WALLET_USER_ID: ${WALLET_USER_ID}
      WALLET_PASSWORD: ${WALLET_PASSWORD}
      INDY_WALLET_URL: ${INDY_WALLET_URL}
      INDY_WALLET_TYPE: ${INDY_WALLET_TYPE}
      REDIS_SERVICE_NAME: ${REDIS_SERVICE_NAME}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      DEBUG: ${DEBUG}
      RUST_LOG: ${RUST_LOG}
      RUST_BACKTRACE: ${RUST_BACKTRACE}
    volumes:
      - on_biz_wallet:/home/indy/.indy_client/wallet
    networks:
      - tob_tob
      - tob_wallet-tob
      - permitify
    ports:
      - 5006:8080
      
networks:
  tob_tob:
    external: true
  tob_wallet-tob:
    external: true
  permitify:

volumes:
  worksafe_bc_wallet:
  bc_registries_wallet:
  ministry_of_finance_wallet:
  fraser_valley_health_authority_wallet:
  city_of_surrey_wallet:
  liquor_control_and_licensing_branch_wallet:
  on_biz_wallet: