version: '3'
services:

  bc_registries:
    image: permitify
    environment:
      # DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
      THE_ORG_BOOK_BASE_URL: 'https://django-devex-von-dev.pathfinder.gov.bc.ca/api/v1'
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: bc_registries
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8080
    # links:
    #   - postgres
    volumes:
      # - ./src:/app
      # - ./site_templates:/app/site_templates
      - bc_registries_wallet:/app/.indy_client/wallet
    ports:
      - 3000:8080


  worksafe_bc:
    image: permitify
    environment:
      # DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
      THE_ORG_BOOK_BASE_URL: 'https://django-devex-von-dev.pathfinder.gov.bc.ca/api/v1'
      DISCONNECTED: '${DISCONNECTED-false}'
      TEMPLATE_NAME: worksafe_bc
      APPLICATION_IP: 0.0.0.0
      APPLICATION_PORT: 8080
    # links:
    #   - postgres
    volumes:
      # - ./src:/app
      # - ./site_templates:/app/site_templates
      - worksafe_bc_wallet:/app/.indy_client/wallet
    ports:
      - 4000:8080



  # Example new service:
  
  # liquor_board:
  #   image: permitify
  #   environment:
  #     # DATABASE_URL: 'postgres://postgres:@postgres:5432/postgres'
  #     THE_ORG_BOOK_BASE_URL: 'https://django-devex-von-dev.pathfinder.gov.bc.ca/api/v1'
  #     DISCONNECTED: '${DISCONNECTED-false}'
  #     TEMPLATE_NAME: liquor_board
  #     APPLICATION_IP: 0.0.0.0
  #     APPLICATION_PORT: 8080
  #   # links:
  #   #   - postgres
  #   volumes:
  #     # - ./src:/app
  #     # - ./site_templates:/app/site_templates
  #     - liquor_board_wallet:/app/.indy_client/wallet
  #   ports:
  #     - 5000:8080


  # postgres:
  #   image: postgres
  #   ports:
  #     - '5432:5432'

volumes:
  worksafe_bc_wallet:
  bc_registries_wallet:
  # liquor_board_wallet:
