issuers:
  ministry-finance:
    logo_path: ''
    name: Fraser Valley Health Authority
    abbreviation: FRV
    email: frv.test.issuer@example.ca

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      
    wallet:
      seed: $WALLET_SEED

    credential_types:
      - description: Operating Permit
        schema: operating_permit.permitify
        issuer_url: $APPLICATION_URL_INCORP
        topic: 
          source_id:
            input: corp_num
            from: claim
          type:
            input: incorporation
            from: value

proof_requests:
  registration:
    version: '1.0.0'
    schemas:
      - key:
          did: 6qnvgJtqwK44D8LFYnV5Yf
          name: incorporation.permitify
          version: '1.0.0'
        attributes:
          - corp_num
