default:
  APPLICATION_URL_INCORP: $APPLICATION_URL/fraser-valley/permit
  TEMPLATE_PATH: ../templates
  TOB_API_URL: http://tob-api:8080/api/v2
  TOB_APP_URL: http://localhost:8080
  FRASER_WALLET_SEED: ministry_frv_dev_000000000000000
