# Agent info
url = ""
template_root = "bcgov.index.html"
name = "BC Corporate Registry"
abbreviation = "BCReg"
jurisdiction_name = "British Columbia"
jurisdiction_abbreviation = "BC"

# This seed must be authorized on the ledger!
wallet_seed = "bc_registries_agent_000000000000"

# Webpage info
title = "BC Corporate Registry"
description = "This is a description"
explanation = "Use the forms below to register a BC corporation."

[[js_includes]]
src = "js/bc_registries.js"

# Forms:
# 
# These structures are used to build the forms
# in the UI.

[[forms]]
name = "incorporation"
title = "Incorporation"

  [[forms.hidden]]
  name = "for_schema"
  value = "incorporation.bc_registries"

  [[forms.inputs]]
  type = "text"
  required = true
  name = "legal_name"
  pretty = "Legal Name"

  [[forms.inputs]]
  type = "address"
  required = true
  name = "address"
  pretty = "Mailing Address"

[[forms]]
name = "doing_business_as"
title = "Doing Business As"

  [[forms.hidden]]
  name = "for_schema"
  value = "doing_business_as.bc_registries"

  [[forms.inputs]]
  type = "text"
  required = true
  name = "legal_entity_id"
  pretty = "Legal Entity ID"

  [[forms.inputs]]
  type = "text"
  required = true
  name = "doing_business_as_name"
  pretty = "Doing Business As Name"

  [[forms.inputs]]
  type = "address"
  required = true
  name = "address"
  pretty = "Mailing Address"

[[forms]]
name = "verify_dba"
action = "/verify_dba"
title = "Verify DBA Name"

  [[forms.inputs]]
  type = "text"
  name = "legal_entity_id"
  required = true
  pretty = "Legal Entity ID"

  [[forms.inputs]]
  type = "text"
  name = "doing_business_as_name"
  required = true
  pretty = "Doing Business As Name"  

# Schema mappers:
# 
# One for each schema type.
# 
# Each mapper is invoked when a request is received
# which contains value "schema" which maps to "for"
# property.

[[schema_mappers]]
for = "incorporation.bc_registries"
  [[schema_mappers.attributes]]
  name = "legal_entity_id"
  from ="helper"
  source = "uuid"

  [[schema_mappers.attributes]]
  name = "corp_num"
  from ="previous"
  source = "legal_entity_id"

  [[schema_mappers.attributes]]
  name = "legal_name"
  from ="request"
  source = "legal_name"

  [[schema_mappers.attributes]]
  name = "org_type"
  from ="literal"
  source = "CO"

  [[schema_mappers.attributes]]
  name = "addressee"
  from ="request"
  source = "addressee"

  [[schema_mappers.attributes]]
  name = "address_line_1"
  from ="request"
  source = "address_line_1"

  [[schema_mappers.attributes]]
  name = "address_line_2"
  from ="request"
  source = "address_line_2"

  [[schema_mappers.attributes]]
  name = "city"
  from ="request"
  source = "city"

  [[schema_mappers.attributes]]
  name = "province"
  from ="request"
  source = "province"

  [[schema_mappers.attributes]]
  name = "postal_code"
  from ="request"
  source = "postal_code"

  [[schema_mappers.attributes]]
  name = "country"
  from ="request"
  source = "country"

  [[schema_mappers.attributes]]
  name = "effective_date"
  from ="helper"
  source = "now"

  [[schema_mappers.attributes]]
  name = "end_date"
  from ="literal"
  # source = null


[[schema_mappers]]
for = "doing_business_as.bc_registries"
  [[schema_mappers.attributes]]
  name = "legal_entity_id"
  from ="helper"
  source = "uuid"

  [[schema_mappers.attributes]]
  name = "corp_num"
  from ="previous"
  source = "legal_entity_id"

  [[schema_mappers.attributes]]
  name = "doing_business_as_name"
  from ="request"
  source = "doing_business_as_name"

  [[schema_mappers.attributes]]
  name = "addressee"
  from ="request"
  source = "addressee"

  [[schema_mappers.attributes]]
  name = "address_line_1"
  from ="request"
  source = "address_line_1"

  [[schema_mappers.attributes]]
  name = "address_line_2"
  from ="request"
  source = "address_line_2"

  [[schema_mappers.attributes]]
  name = "city"
  from ="request"
  source = "city"

  [[schema_mappers.attributes]]
  name = "province"
  from ="request"
  source = "province"

  [[schema_mappers.attributes]]
  name = "postal_code"
  from ="request"
  source = "postal_code"

  [[schema_mappers.attributes]]
  name = "country"
  from ="request"
  source = "country"

  [[schema_mappers.attributes]]
  name = "effective_date"
  from ="helper"
  source = "now"

  [[schema_mappers.attributes]]
  name = "end_date"
  from ="literal"
  # source = null
