issuers:
  ministry-finance:
    name: BC Ministry of Finance
    abbreviation: Ministry of Finance
    email: minfinance.test.issuer@example.ca

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      
    wallet:
      seed: $WALLET_SEED_BCREG

    credential_types:
      - description: PST Number
        schema: pst_number.permitify
        issuer_url: $APPLICATION_URL_INCORP
        topic: 
          source_id:
            input: corp_num
            from: claim
          type:
            input: incorporation
            from: value
        mapping:
          - model: name
            fields:
              text:
                input: TEST
                from: value
              type:
                input: legal_name
                from: value

proof_requests:
  registration:
    version: '1.0.0'
    schemas:
      - key:
          name: incorporation.permitify
          version: '1.0.0'
        attributes:
          - corp_num
          - address_line_1
          - address_line_2
          - addressee
          - city
          - country
          - legal_name
          - postal_code
          - province
